### ISSUE TITLE
Define and implement configuration strategy

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#46]
Users will need to be able to configure the workflow quite extensively, e.g.,:

- Which plugins should be run?
- How to map alternative email addresses?
- ...

We need to define a confiuration strategy that includes a number of things:

- Should there be a one-size-fits-all config file?
- Should there be additionally a way to configure as params?
- Should we wrap, or simply reuse, native solutions such as `.mailmap` (standard git email mapping config)?

This strategy will have to satisfy a good UX! 

E.g., as a HERMES user, I may not know about `.mailmap` or similar, and may not want to be bothered with another config file, especially when I'm already working with one thing (the HERMES config).

**Comment by led02** [comment]
I would prefer "native solutions" where possible, just because they are then picked up by other tools, too. (No duplication required.)

However, I also see a problem because a clean approach would mean to also use "native solutions" in the other direction. I.e., HERMES should automatically identify what kind of project it is applied to and detect relevant configuration files (e.g., `pyproject.tom`, `pom.xml`, `Cargo.toml`, ...). This would however be just too much different possibilities to handle.

Hence, my proposal is:

- Have a unified, independent `hermes.toml`
- Support the user in using "native solutions" (like `.mailmap`, which is not read by Hermes tool at all but leads to expected results)
- Keep in mind for later that using the "build configuration" file might be an extensible solution.

**Comment by sdruskat** [comment]
I agree with a unified config for hermes.

- **question:** Why `.toml` rather than `.yml`?
- **question:** If we support the user in using native solutions, but don't pick it up later, isn't this either out-of-scope, or wasted time?
    - **suggestion:** Can we support both approaches at the same time, leaving it up to the user, which configuration path to choose? I.e., implement support for `.mailmap`-style mail mapping in `hermes.*ml` (and prefer that over native solutions, as it is more expressive), but fall back to native solutions if it isn't configured?

**Comment by sdruskat** [comment]
See also #39 for a more implementation-centric discussion.

**Comment by sdruskat** [comment]
Decisions:

- We wil provide a Python script tied to a `hermes` command that lets users update configuration files
- We'll use `hermes.conf` in TOML
- Native solutions are not yet systematically supported, although they're useful to support for users. Tracking this in #102.
