### ISSUE TITLE
Implement Invenio mapper

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#58]
We need to implement a mapper from internal data model to whatever the pub repo accepts.

**Comment by zyzzyxdonta** [comment]
I started implementing the mapping in #125. It's relatively straight forward (aside from some gaps/assumptions caused by the configurable mapping stuff that is still missing). Unfortunately though, just following a schema that can be used for validation, is not possible. :-(

In #105 I implemented download of the metadata schema for Invenio records from this URL (as discussed in https://github.com/hermes-hmc/workflow/issues/55) :

- [api/schemas/records/record-v1.0.0.json](https://zenodo.org/api/schemas/records/record-v1.0.0.json)

I then found, that there's also this schema:

- [api/schemas/deposits/records/record-v1.0.0.json](https://zenodo.org/api/schemas/deposits/records/record-v1.0.0.json)

(The two schemas differ a tiny bit.)

Neither of these schemas describe the correct "deposition metadata" that expected when creating a deposit. This is only described here:

- https://developers.zenodo.org/#representation

There are some differences between this description and the schemas:

- `creators`/`contributors` may only have a `name`, not `givenName` and `familyName`
- `license` is just a string; in the schemas it must be an object (possibly following [this](http://zenodo.org/schemas/licenses/license-v1.0.0.json) schema?)
- there is `upload_type` instead of `resource_type`
- probably some others I missed

And most importantly, there is no API URL that provides a schema for this...
