### ISSUE TITLE
Set up documentation

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#7]
We need the following documentation:

- User docs (plain text)
    - End users
    - Insitutional users (e.g., users that set up, extend, configure the workflow for their own instances of target repos)
- Dev docs
    - docstrings (rendered into package docs)
    - plain text docs
    - ADRs
- Contribution documentation (cf. #5)

The question is:

- Should we provide all docs types in one "document", alternatively, use dedicated tooling for each type (or a subset)

**Comment by sdruskat** [comment]
Suggestion: make this a common docs project to avoid the use of too many tools.

Concretely: Sphinx + MyST (to be able to write Markdown).

Any opinions, @poikilotherm, @knodel, @juckel?

**Comment by juckel** [comment]
I honestly cannot contribute much to this discussion due to a lack of hands-on experience. So far I have only edited existing documentation. From very far away I would have the low level code documentation as part of the code(s). The user and high level developer documentation I would put together into two different sections/chapters of the online documentation.

**Comment by sdruskat** [comment]
Comment by @poikilotherm from the jour fixe: RST can do some things more nicely, e.g., PlantUML, linking, etc.
